version:  '1.0.0'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/home/app/backend/src
    depends_on:
      - db
  db:
    image: mongo:8.0.3-noble
    container_name: db-app
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db # Persistent storage for MongoDB

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data: # Named volume for MongoDB data persistence
